openapi: 3.0.1
info:
  title: Fefe Restaurant
  version: 1.0.0
  description: This is a sample API created to ilustrated how can a Node.Js be documented using Swagger UI
servers:
- url: http://localhost:10010/v1
- url: https://localhost:10010/v1
paths:
  /recipies:
    get:
      operationId: getRecipies
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Recipe'
                type: array
          description: All recipies were fetch
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
          description: Server Error
      summary: Return all recipies
      x-eov-operation-handler: controllers/DefaultController
    post:
      operationId: postRecipies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
        description: Recipie to add
        required: true
      responses:
        "204":
          content: {}
          description: Success
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
          description: Server Error
      summary: Create a new recipie
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/DefaultController
    put:
      operationId: updateRecipe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
        required: true
      responses:
        "204":
          content: {}
          description: Success
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
          description: Server Error
      summary: Updates an Existing recipie with the given ID
      x-codegen-request-body-name: Recipe
      x-eov-operation-handler: controllers/DefaultController
    x-swagger-router-controller: recipe
  /recipes/{recipeId}:
    delete:
      operationId: deleteRecipe
      parameters:
      - explode: false
        in: path
        name: recipeId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "204":
          content: {}
          description: Success
        "404":
          content: {}
          description: Id dosn't exist
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
          description: Server Error
      summary: Delete a Recipe
      x-eov-operation-handler: controllers/DefaultController
    x-swagger-router-controller: recipe
  /recipe/{recipeId}/comment:
    get:
      operationId: getRecipeComments
      parameters:
      - explode: false
        in: path
        name: recipeId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Comment'
                type: array
          description: Comment fetch success
        "404":
          content: {}
          description: Invalid Id
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
          description: Server Error
      summary: Gets all the comments for the given recipe
      x-eov-operation-handler: controllers/DefaultController
    post:
      operationId: postComment
      parameters:
      - explode: false
        in: path
        name: recipeId
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
        required: true
      responses:
        "204":
          content: {}
          description: Success
        "404":
          content: {}
          description: Invalid Id
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
          description: Server Error
      summary: Creates a new comment
      x-codegen-request-body-name: Comment
      x-eov-operation-handler: controllers/DefaultController
    x-swagger-router-controller: recipe
  /recipies/{recipeId}/comment/{commentId}:
    delete:
      operationId: deleteComment
      parameters:
      - explode: false
        in: path
        name: recipeId
        required: true
        schema:
          type: integer
        style: simple
      - explode: false
        in: path
        name: commentId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "204":
          content: {}
          description: Success
        "404":
          content: {}
          description: Invalid id
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
          description: Server Error
      summary: Deletes the comment of the provided id.
      x-eov-operation-handler: controllers/DefaultController
    put:
      operationId: updateComment
      parameters:
      - explode: false
        in: path
        name: recipeId
        required: true
        schema:
          type: integer
        style: simple
      - explode: false
        in: path
        name: commentId
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
        required: true
      responses:
        "204":
          content: {}
          description: Success
        "404":
          content: {}
          description: Invalid id
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
          description: Server Error
      summary: Updates The comment.
      x-codegen-request-body-name: Comment
      x-eov-operation-handler: controllers/DefaultController
    x-swagger-router-controller: recipe
  /swagger:
    x-swagger-pipe: swagger_raw
components:
  schemas:
    Recipe:
      example:
        name: name
        chef: Joao
        isPublic: true
        ingredients:
        - amount: 6.027456183070403
          name: name
        - amount: 6.027456183070403
          name: name
        id: 0
        stepList:
        - stepList
        - stepList
      properties:
        id:
          type: integer
        isPublic:
          type: boolean
        name:
          type: string
        chef:
          enum:
          - Joao
          - Charles
          type: string
        stepList:
          items:
            type: string
          type: array
        ingredients:
          items:
            $ref: '#/components/schemas/Recipe_ingredients'
          type: array
      type: object
    Comment:
      example:
        date: date
        author: author
        id: 0
        text: text
        recipeId: 6
      properties:
        id:
          type: integer
        recipeId:
          type: integer
        author:
          type: string
        text:
          type: string
        date:
          type: string
      type: object
    inline_response_500:
      properties:
        messege:
          type: string
    Recipe_ingredients:
      example:
        amount: 6.027456183070403
        name: name
      properties:
        amount:
          type: number
        name:
          type: string
